# Generated by Django 3.2.7 on 2021-09-04 10:37

from django.db import migrations, models

import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
            ],
            bases=(models.Model, django_prometheus.models.ExportModelOperationsMixin('task')),
        ),
    ]
